[versions]
agp = "8.12.3"
kotlin = "2.2.20"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
lifecycleRuntimeKtx = "2.9.4"

zendesk-messaging = "2.36.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
zendesk-messaging-android = { group = "zendesk.messaging", name = "messaging-android", version.ref = "zendesk-messaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
